#!/bin/sh

MAIN_MONITOR="DP-0"
PEN_MONITOR="DP-3"
SECOND_MONITOR="HDMI-0"


if [[ -n $(xrandr --listactivemonitors | grep "eDP-1") ]]; then
	# LAPTOP CONFIG
	bspc monitor -d 1 2 3 4 5 6 7
else
	# DESKTOP CONFIG
	### WORKSPACES ###
	bspc monitor $MAIN_MONITOR -d nvim obs util
	bspc monitor $SECOND_MONITOR -d web term extra
	bspc monitor $PEN_MONITOR -d draw

	### CONFIGURATION ###
	bspc config remove_disabled_monitors true
	bspc config remove_unplugged_monitors true


	xrandr --output $MAIN_MONITOR --mode 1920x1080 --rate 143 --pos 0x0 --primary --output $SECOND_MONITOR --mode 1920x1080 --left-of $MAIN_MONITOR --output $PEN_MONITOR --mode 1920x1080 --right-of $MAIN_MONITOR

fi

bspc config border_width         2
bspc config window_gap           4
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#101010"
bspc config focused_border_color "#00a9c9"

### AUTOSTART ###
pgrep -x sxhkd > /dev/null || sxhkd &
killall -q dunst
dunst &
killall -q picom 
picom &
killall -q greenclip
greenclip daemon &
# Launch polybar
$HOME/.config/polybar/launch.sh


# remove unwanted Desktop
bspc desktop Desktop --remove

if [[ -n $(xrandr | grep "eDP-1") ]]; then
	feh --bg-fill ~/m/media/pic/walls/japanstyle_eagle.jpg
	bspc rule -a firefox desktop=^4
	bspc rule -a obsidian desktop=^5
else
	$HOME/bin/pen_display_setup.sh &
	feh --bg-fill ~/m/media/pic/walls/NierAutomata.jpg

	### RULES ###
	bspc rule -a pavucontrol state=floating
	bspc rule -a discord state=floating
	bspc rule -a yad-calendar state=floating
	bspc rule -a firefox desktop=web
	bspc rule -a Spotify desktop=extra
	bspc rule -a obsidian desktop=obs
fi
