console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  blue = '#1d9ec1'
  green = '#6ae458'
  orange = '#a874ce'
  red = '#f265b5'
  white = '#aedbf0'
  yellow = '#03b6b0'

[secondary_prompt]
  template = '<p:yellow,transparent></><p:yellow> > </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[transient_prompt]
  template = '<p:yellow,transparent>❱</> '
  foreground = 'p:white'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

# User block
	[[blocks.segments]]
    template = '{{ if .SSHSession }} {{ end }}󰣇 <b><p:black>{{ .UserName }}</> '
    foreground = 'p:orange'
    background = 'p:yellow'
    type = 'session'
    style = 'diamond'
		leading_diamond= ""
		trailing_diamond = ""

# Git block
  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:black'
    leading_diamond = ''
    trailing_diamond = ''
    background = 'p:green'
    type = 'git'
    style = 'diamond'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true
# Path block
	[[blocks.segments]]
		type = 'path'
		style = "diamond"
		leading_diamond= ""
		trailing_diamond = ""
		background = 'p:orange'
		foreground = 'p:white'
		template = ' <b><p:white>{{ .Path }}</b></> '

# Right Prompt
[[blocks]]
  type = 'rprompt'
  [[blocks.segments]]
    template = ' {{ if gt .Code 0 }}<p:red> </>{{ else }}<p:green> </>{{ end }}'
    foreground = 'p:white'
    background = 'transparent'
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    template = '  {{if .Venv}}({{ .Venv }}){{ end }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = true

  [[blocks.segments]]
    template = ' <p:blue><b>{{ .Name }}</b></> '
    foreground = 'p:white'
    background = 'transparent'
    type = 'shell'
    style = 'plain'

  [[blocks.segments]]
    template = '<p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
    foreground = 'p:white'
    background = 'transparent'
    type = 'time'
    style = 'plain'

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'p:white'
  background = 'p:orange'
  type = 'aws'
  style = 'diamond'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  foreground = 'p:white'
  background = 'p:blue'
  type = 'az'
  style = 'diamond'
  tips = ['az']

  [tooltips.properties]
    display_default = true
